require('plugin-configs/github-theme')
require('plugin-configs/nvim-lspconfig')
require('plugin-configs/nvim-tree')
require('plugin-configs/telescope')
require('plugin-configs/mason')
require('plugin-configs/lualine')